version: '3'
services:
  node_pizza:
    image: pizza-express:latest
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis
    ports:
      - "8081:3000"
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"